[tool.uv]
dev-dependencies = [
    "pytest==8.3.2",
    "hypothesis==6.112.0",
    "pytest-asyncio==0.24.0",
    "pytest-xdist[psutil]==3.6.1",
    "ruff==0.6.8",
    "mypy==1.13.0",
    "types-pytz==2024.2.0.20241003",
]

[tool.pdm.build]
includes = []

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[project]
authors = [{ name = "trumully", email = "truman.mulholland@gmail.com" }]
license = { text = "LICENSE" }
requires-python = "==3.13.0"
dependencies = [
    "discord-py[speed] @ git+https://github.com/mikeshardmind/discord.py.git@89ac64f",
    "click==8.1.7",
    "toml==0.10.2",
    "python-dateutil==2.9.0.post0",
    "platformdirs==4.2.2",
    "xxhash==3.5.0",
    "base2048==0.1.3",
    "numpy==2.1.0",
    "msgspec @ git+https://github.com/jcrist/msgspec@main",
    "pillow==10.4.0",
    "truststore==0.9.2",
    "types-python-dateutil==2.9.0.20240906",
    "rapidfuzz==3.9.7",
    "apsw==3.46.1.0",
    "pygit2==1.16.0",
    "arrow==1.3.0",
    "pytz==2024.2",
]
name = "dynamo"
version = "0.2.0"
description = "Quantum entanglement!"
readme = "README.md"

[project.scripts]
dynamo = "dynamo.runner:main"

[tool.ruff]
target-version = "py313"
line-length = 120

[tool.ruff.lint]
select = [
    "F",
    "E",
    "I",
    "UP",
    "YTT",
    "ANN",
    "S",
    "BLE",
    "B",
    "A",
    "COM",
    "C4",
    "DTZ",
    "EM",
    "ISC",
    "G",
    "INP",
    "PIE",
    "T20",
    "Q003",
    "RSE",
    "RET",
    "SIM",
    "TID",
    "PTH",
    "ERA",
    "PD",
    "PLC",
    "PLE",
    "PLR",
    "PLW",
    "TRY",
    "NPY",
    "RUF",
    "ASYNC",
]
ignore = [
    "A005",
    "RUF001",
    "RUF029",
    "G002",
    "S101",
    "PLR2004",
    "PLC0105",
    "PLC0415",
    "PLR0917",
    "SIM105",
    "C90",
    "ANN101",
    "ANN202",
    "ANN204",
    "ANN401",
    "PLR0912",
    "PLR0913",
    "PLR0915",
    "PLW3201",
    "UP007",
    "COM812",
    "ISC001",
    "B008",
    "ASYNC109",
    "E999",
    "PLR6301",

]
unfixable = ["ERA"]

[tool.pytest.ini_options]
asyncio_mode = "strict"
asyncio_default_fixture_loop_scope = "function"
filterwarnings = [
    "ignore:'audioop' is deprecated and slated for removal in Python 3.13:DeprecationWarning",
]

[tool.mypy]
python_version = "3.13"
packages = ["dynamo"]
disallow_untyped_defs = true
disallow_any_unimported = true
check_untyped_defs = true
warn_return_any = true
warn_unused_ignores = true
warn_unused_configs = true
ignore_missing_imports = true
