name: 🚀 Feature Request
description: Suggest a new feature or enhancement.
title: "[Feature] "
labels: ["enhancement"]
projects: ["trumully/1"]
body:
  - type: textarea
    attributes:
      label: Feature Description
      description: A concise description of the feature you're proposing.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Implementation
      description: If you have ideas, suggest how this feature could be implemented.
      placeholder: |
        1. Add this component
        2. Modify that function
        3. Update the UI here
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or examples about the feature request.
    validations:
      required: false
