name: Test


on:
  push:
    branches:
      - main
    paths:
      - dynamo/**/*.py
      - tests/**/*.py
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - dynamo/**/*.py
      - tests/**/*.py

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  tests:
    name: Test with pytest
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'poetry'
      - run: poetry install --with=dev
      - run: poetry run pytest tests --asyncio-mode=strict -n logical
